### ISSUE TITLE
hostname instead of 127.0.0.1

### ISSUE THREAD

**Issue by pfefferle** [voxpelli/node-webmention-testpinger#11]
I tried to use the testpinger in different environments and for example with docker and therefore it would be nice to use the hostname instead of the localhost IP address. Perhaps it might be enough to make it configurable.

**Comment by voxpelli** [comment]
Sounds good to make it configurable! I'll merge a PR or else I get to it once I finally get around to do a new release of this module which I really should try to do vert soon :)
