### ISSUE TITLE
"normal" website

### ISSUE THREAD

**Issue by pfefferle** [voxpelli/node-webmention-testpinger#7]
Adding a "normal" website with mf1 or no mf support (or both), to test the fallback and or the handling of semantic-less sites.

**Comment by voxpelli** [comment]
@pfefferle I wonder if we should make a `basic-html` one that's super basic or take the HTML of a more standard basic HTML page and include that? Could probably be good to include a normal one with open graph data and one without it – what do you think?

**Comment by pfefferle** [comment]
Sounds good! I also like the idea to include an OpenGraph and/or schema.org example!
